services:

  faucet-ui:
    image: node:16
    restart: always
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./:/app
    ports:
      - 3002:3000
